### ISSUE TITLE
Cannot load ProteoWizard dlls

### ISSUE THREAD

**Issue by mobiusklein** [PNNL-Comp-Mass-Spec/DeconTools#1]
Attempting to use the latest released installer version of DeconConsole.exe on an mzML file with a recent build of 64-bit Proteowizard on Windows 10 produced the following error:

```
Starting..............
Dataset = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX # Removed for brevity
Cannot load ProteoWizard dlls. Please ensure that 64-bit ProteoWizard is installed to its default install directory ("C:\Program Files\ProteoWizard\ProteoWizard 3.0.[x]").
Currently trying to load ProteoWizard dlls from path "C:\Program Files\ProteoWizard\ProteoWizard 3.0.9740".

-------------------------------------------- ERROR! -------------------------------------------------
A fatal error occured when connecting to the instrument data file. Could not create the Run object. Internal error message: Cannot load ProteoWizard dlls. Please ensure that 64-bit ProteoWizard is installed to its default install directory ("C:\Program Files\ProteoWizard\ProteoWizard 3.0.[x]").
Currently trying to load ProteoWizard dlls from path "C:\Program Files\ProteoWizard\ProteoWizard 3.0.9740".

   at pwiz.ProteowizardWrapper.DependencyLoader.ValidateLoader()
   at DeconTools.Backend.Runs.RunFactory.CreateRun(String filename) in F:\My Documents\Projects\GordonSlysz\DeconTools_IQ\DeconTools.Backend\Runs\RunFactory.cs:line 36
   at DeconTools.Backend.Workflows.ScanBasedWorkflow.CreateWorkflow(String datasetFileName, String parameterFile, String outputFolderPath, BackgroundWorker backgroundWorker, Boolean useNewDeconToolsParameterObjects) in F:\My Documents\Projects\GordonSlysz\DeconTools_IQ\DeconTools.Backend\Workflows\ScanBasedWorkflow.cs:line 84
```
This problem also occurs on a Windows 7 computer with a fresh installation of Proteowizard and a fresh download of the DeconTools installer. DeconConsole.exe worked without issue when used on a Thermo Fisher RAW file. This problem occurs on both DeconConsole and the Autoprocessor GUI. 

Three other notes:
1. In the latest installer ZIP from https://omics.pnl.gov/software/decontools-decon2ls, the DeconTools/ directory does not contain "DeconToolsAutoProcessV1.exe", but is present in the installed location "C:\Program Files (x86)\DeconTools\DeconToolsAutoProcessV1.exe".
2. The 64-bit installer installs into "C:\Program Files (x86)\"
3. The error message contains the absolute path to a source file on one of the original author's computer, Gordon Slysz on the last line

**Comment by FarmGeek4Life** [comment]
Thank you for reporting this, I'll look into this next week. Thank you also for mentioning the bad install directory for the 64-bit installer. Also, the file path is not significant, beyond telling me in which file the error occurred. The file path only appears because we currently package the .pdb files with the program, and the path shown is the path to the source on whichever computer the program was last compiled on.

**Comment by FarmGeek4Life** [comment]
@mobiusklein in the install directory (C:\Program Files (x86)\...) is there a file named "pwiz_bindings_cli.dll"? If there is, delete it and try to run DeconTools again. The check that provided the above error message doesn't check the location where it finds and fails to load the DLL.

**Comment by mobiusklein** [comment]
I uninstalled DeconTools, and then created a fresh installation. `pwiz_bindings_cli.dll` was not present in the installation directory. Re-running the example, I receive the same error message.
From the BAD_ERROR log file:

```
7/5/2017 2:32:23 PM	DeconTools.Backend.dll version = v2.0.6148.31366
7/5/2017 2:32:23 PM	UIMFLibrary version = v3.0.6089.26360
7/5/2017 2:32:23 PM	ERROR message= Cannot load ProteoWizard dlls. Please ensure that 64-bit ProteoWizard is installed to its default install directory ("C:\Program Files\ProteoWizard\ProteoWizard 3.0.[x]").
Currently trying to load ProteoWizard dlls from path "C:\Program Files\ProteoWizard\ProteoWizard 3.0.9740".
7/5/2017 2:32:23 PM	ERROR type= System.TypeLoadException: Cannot load ProteoWizard dlls. Please ensure that 64-bit ProteoWizard is installed to its default install directory ("C:\Program Files\ProteoWizard\ProteoWizard 3.0.[x]").
Currently trying to load ProteoWizard dlls from path "C:\Program Files\ProteoWizard\ProteoWizard 3.0.9740".
   at pwiz.ProteowizardWrapper.DependencyLoader.ValidateLoader()
   at DeconTools.Backend.Runs.RunFactory.CreateRun(String filename) in F:\My Documents\Projects\GordonSlysz\DeconTools_IQ\DeconTools.Backend\Runs\RunFactory.cs:line 36
   at DeconTools.Backend.Workflows.ScanBasedWorkflow.CreateWorkflow(String datasetFileName, String parameterFile, String outputFolderPath, BackgroundWorker backgroundWorker, Boolean useNewDeconToolsParameterObjects) in F:\My Documents\Projects\GordonSlysz\DeconTools_IQ\DeconTools.Backend\Workflows\ScanBasedWorkflow.cs:line 84
7/5/2017 2:32:23 PM	STACKTRACE =    at pwiz.ProteowizardWrapper.DependencyLoader.ValidateLoader()
   at DeconTools.Backend.Runs.RunFactory.CreateRun(String filename) in F:\My Documents\Projects\GordonSlysz\DeconTools_IQ\DeconTools.Backend\Runs\RunFactory.cs:line 36
   at DeconTools.Backend.Workflows.ScanBasedWorkflow.CreateWorkflow(String datasetFileName, String parameterFile, String outputFolderPath, BackgroundWorker backgroundWorker, Boolean useNewDeconToolsParameterObjects) in F:\My Documents\Projects\GordonSlysz\DeconTools_IQ\DeconTools.Backend\Workflows\ScanBasedWorkflow.cs:line 84
```

**Comment by FarmGeek4Life** [comment]
@mobiusklein I found the issue, I need to update the files on omics.pnl.gov. A code change in June 2016 removed a function call that allowed the program to find the proteowizard dlls in their install folder.

**Comment by FarmGeek4Life** [comment]
I have updated the downloads at https://omics.pnl.gov/software/decontools-decon2ls with the updated code. The new version does require that .Net 4.6.2 be installed, due to other non-related changes in dependencies.

**Comment by mobiusklein** [comment]
I uninstalled the previous version, upgraded to the latest version of .NET (4.7), and installed the 64 bit version. Running DeconConsole.exe using the same parameters as before, I receive 
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'PRISM, Version=2.4.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at DeconConsole.Program.Main(String[] args)
```
The file "PRISM.dll" is absent from the installation directory, but it is present in the DeconTools_x64/86 directories. When ran from these in-place deploy directories in your download bundle, the program appears to run now.

I'll run some follow up tests on the resulting output to check that it looks approximately right.

**Comment by FarmGeek4Life** [comment]
Thank you also for that report, that will be fixed in future releases.

**Comment by FarmGeek4Life** [comment]
Closing, with the assumption that there were no further issues.
