### ISSUE TITLE
Not quite sure how to download

### ISSUE THREAD

**Issue by ruimikec** [PNNL-Comp-Mass-Spec/DeconTools#4]
Trying to download using C# on Visual Studio, but it is saying it cannot find the 4.2 version. The text file in Bin says to compile the DeconConsole.exe using the .sln file - but I'm not sure how to do this and the installation instructions aren't very clear. I'm sorry if I'm missing something obvious. I also tried download the GUI via powershell with the .iss file. 

Thank you,

M

**Comment by alchemistmatt** [comment]
I need to update the Readme to point people to the Releases page.  I suspect you only want the executable; you can find that at https://github.com/PNNL-Comp-Mass-Spec/DeconTools/releases
I suggest you download and run DeconTools_Installer.exe

**Comment by ruimikec** [comment]
Thanks!
