### ISSUE TITLE
Unexpected behavior in getAvereage()

### ISSUE THREAD

**Issue by ksmiller99** [PNNL-Comp-Mass-Spec/DeconTools#5]
In DeconTools.Backend.Utilities.MathUtils.GetAverage(double[] values), if the sum exceeds either double.MaxValue or double.MinValue, instead of returning NaN or throwing an exception, the method returns double.PositiveInfinity or double.NegativeInfinity. Is this the expected behavior? The data set does have an average, but that is not what is returned. 

I'm using C# 7.3 in MSVS 2019.

Thanks,
Kevin

**Comment by alchemistmatt** [comment]
I agree, that's not ideal. To my knowledge we haven't encountered lists of data whose sum surpasses infinity.  I will update the code to use Math.NET Numerics, specifically
`MathNet.Numerics.Statistics.Statistics.Mean(values);`

**Comment by alchemistmatt** [comment]
Fixed with commit 4a0563df26

Update binaries are at https://github.com/PNNL-Comp-Mass-Spec/DeconTools/releases/tag/v1.1.7101
