### ISSUE TITLE
Decon2LS is not perfoming deisotoping.

### ISSUE THREAD

**Issue by Acedon95** [PNNL-Comp-Mass-Spec/DeconTools#7]
Hi,

i was trying to use your program to deisotope some data for my bachelors exam, but the list of deisotoped peaks always remained empty. So i thought maybe my data is wrong in some way so i tried one of your ExampleData files specifically the  QC_Shew_18_02_Excerpt.mzML dataset with the corresponding LTQ_Orb_SN2_PeakBR2_PeptideBR1_Thrash_Sum3.xml which you provided with the program files. I haven't changed a single thing in these files, but i still get an empty QC_Shew_18_02_Excerpt_isos file,as well with the GUI version as with the DeconConsole version of the programm. 

I am working on a Windows 10 machine and installed Decon2LS with the latest installer from your release page.

Is there something i'm doing wrong? I hope you can help me.
I will attach the empty result files so you can see for your self what i mean.

[QC_Shew_18_02_Excerpt_scans.csv](https://github.com/PNNL-Comp-Mass-Spec/DeconTools/files/6377893/QC_Shew_18_02_Excerpt_scans.csv)
[QC_Shew_18_02_Excerpt_peaks.txt](https://github.com/PNNL-Comp-Mass-Spec/DeconTools/files/6377894/QC_Shew_18_02_Excerpt_peaks.txt)
[QC_Shew_18_02_Excerpt_isos.csv](https://github.com/PNNL-Comp-Mass-Spec/DeconTools/files/6377895/QC_Shew_18_02_Excerpt_isos.csv)
[QC_Shew_18_02_Excerpt_log.txt](https://github.com/PNNL-Comp-Mass-Spec/DeconTools/files/6377897/QC_Shew_18_02_Excerpt_log.txt)

**Comment by alchemistmatt** [comment]
I downloaded DeconTools_x64.zip from the newest release at https://github.com/PNNL-Comp-Mass-Spec/DeconTools/releases/ and extracted the files.
I next downloaded the 3 files from the [ExampleData directory](https://github.com/PNNL-Comp-Mass-Spec/DeconTools/tree/master/ExampleData/QExactHF_mzML)
* For the .mzML file, go to the [QC_Shew_18_02_Excerpt.mzML file info page](https://github.com/PNNL-Comp-Mass-Spec/DeconTools/blob/master/ExampleData/QExactHF_mzML/QC_Shew_18_02_Excerpt.mzML) and right click the "Download" button and choose "Save link as"
* Similarly, for the .xml parameter file, go to the [LTQ_Orb_SN2_PeakBR2_PeptideBR1_Thrash_Sum3.xml file info page](https://github.com/PNNL-Comp-Mass-Spec/DeconTools/blob/master/ExampleData/QExactHF_mzML/LTQ_Orb_SN2_PeakBR2_PeptideBR1_Thrash_Sum3.xml) and click "Raw", then right click and choose "Save As"
Running things with a modified version of the command shown in the .bat file gives this:

```
DeconConsole.exe QC_Shew_18_02_Excerpt.mzML LTQ_Orb_SN2_PeakBR2_PeptideBR1_Thrash_Sum3.xml

Starting..............
Dataset:        QC_Shew_18_02_Excerpt.mzML
Full path:      F:\Temp\DeconTools\QC_Shew_18_02_Excerpt.mzML
Parameter file: F:\Temp\DeconTools\LTQ_Orb_SN2_PeakBR2_PeptideBR1_Thrash_Sum3.xml
Searching for ProteoWizard files...
4/27/2021 10:36:27 AM   Scan/Frame= 117; PercentComplete= 12.7; AccumulatedFeatures= 82; ScansProcessed= 9; ScansPerMinute= 90.0
4/27/2021 10:36:28 AM   Scan/Frame= 241; PercentComplete= 25.3; AccumulatedFeatures= 171; ScansProcessed= 19; ScansPerMinute= 190.0
4/27/2021 10:36:29 AM   Scan/Frame= 371; PercentComplete= 38.0; AccumulatedFeatures= 247; ScansProcessed= 29; ScansPerMinute= 290.0
4/27/2021 10:36:29 AM   Scan/Frame= 487; PercentComplete= 50.6; AccumulatedFeatures= 298; ScansProcessed= 39; ScansPerMinute= 390.0
4/27/2021 10:36:30 AM   Scan/Frame= 617; PercentComplete= 63.3; AccumulatedFeatures= 393; ScansProcessed= 49; ScansPerMinute= 490.0
4/27/2021 10:36:31 AM   Scan/Frame= 747; PercentComplete= 75.9; AccumulatedFeatures= 472; ScansProcessed= 59; ScansPerMinute= 590.0
4/27/2021 10:36:32 AM   Scan/Frame= 877; PercentComplete= 88.6; AccumulatedFeatures= 562; ScansProcessed= 69; ScansPerMinute= 690.0


****************************************
****************************************
************** SUCCESS! ****************
****************************************
****************************************
```

Here are the newly created files:
```
04/27/2021  10:36 AM            55,437 QC_Shew_18_02_Excerpt_isos.csv
04/27/2021  10:36 AM             1,352 QC_Shew_18_02_Excerpt_log.txt
04/27/2021  10:36 AM             4,457 QC_Shew_18_02_Excerpt_scans.csv
```

I next downloaded DeconTools_Installer_x64.zip from https://github.com/PNNL-Comp-Mass-Spec/DeconTools/releases/ , extracted the installer, and installed the program.

I then repeated the test, but using the path to the newly installed .exe:
```
"C:\Program Files\DeconTools\DeconConsole.exe" QC_Shew_18_02_Excerpt.mzML LTQ_Orb_SN2_PeakBR2_PeptideBR1_Thrash_Sum3.xml
```

This created the same three files.  As mentioned in the Readme, you need to have ProteoWizard installed, with the files residing in a directory below C:\Program Files\ProteoWizard
* Example ProteoWizard installation path: C:\Program Files\ProteoWizard\ProteoWizard 3.0.21117.90b339fcf
* Alternatively, you can manually copy/move the ProteoWizard files to C:\DMS_Programs\ProteoWizard

If you don't have ProteoWizard installed, you'll see this:
```
Starting..............
Dataset:        QC_Shew_18_02_Excerpt.mzML
Full path:      C:\Temp\DeconTools\QC_Shew_18_02_Excerpt.mzML
Parameter file: C:\Temp\DeconTools\LTQ_Orb_SN2_PeakBR2_PeptideBR1_Thrash_Sum3.xml
Searching for ProteoWizard files...
Cannot load ProteoWizard DLLs. Please ensure that 64-bit ProteoWizard is installed to its default install directory ("C:\Program Files\ProteoWizard\ProteoWizard 3.0.[x]").
Currently trying to load ProteoWizard DLLs from path "".
Cannot load ProteoWizard DLLs. Please ensure that 64-bit ProteoWizard is installed to its default install directory ("C:\Program Files\ProteoWizard\ProteoWizard 3.0.[x]").
Currently trying to load ProteoWizard DLLs from path "".

-------------------------------------------- ERROR! -------------------------------------------------
A fatal error occurred when connecting to the instrument data file. Could not create the Run object. Internal error message: The type initializer for 'pwiz.ProteowizardWrapper.DependencyLoader' threw an exception.

Stack trace:
  DeconTools.Backend.Workflows.ScanBasedWorkflow.CreateWorkflow
  DeconTools.Backend.Runs.RunFactory.CreateRun

Cannot load ProteoWizard DLLs. Please ensure that 64-bit ProteoWizard is installed to its default install directory ("C:\Program Files\ProteoWizard\ProteoWizard 3.0.[x]").
```
Comparing your QC_Shew_18_02_Excerpt_log.txt to my QC_Shew_18_02_Excerpt_log.txt file, I believe the issue might be the decimal point symbol.  My log file shows
```
04/27/2021 10:36:26	DeconTools.Backend.dll version = v2.0.7675.31322
04/27/2021 10:36:26	ParameterFile = LTQ_Orb_SN2_PeakBR2_PeptideBR1_Thrash_Sum3.xml
04/27/2021 10:36:26	UIMFLibrary version = v3.7.3.0
04/27/2021 10:36:27	Scan/Frame= 117; PercentComplete= 12.7; AccumulatedFeatures= 82; ScansProcessed= 9; ScansPerMinute= 90.0
04/27/2021 10:36:28	Scan/Frame= 241; PercentComplete= 25.3; AccumulatedFeatures= 171; ScansProcessed= 19; ScansPerMinute= 190.0
04/27/2021 10:36:29	Scan/Frame= 371; PercentComplete= 38.0; AccumulatedFeatures= 247; ScansProcessed= 29; ScansPerMinute= 290.0
etc.
```

Yours has
```
04/26/2021 16:24:00	DeconTools.Backend.dll version = v2.0.7675.31322
04/26/2021 16:24:00	ParameterFile = LTQ_Orb_SN2_PeakBR2_PeptideBR1_Thrash_Sum3.xml
04/26/2021 16:24:00	UIMFLibrary version = v3.7.3.0
04/26/2021 16:24:00	Scan/Frame= 117; PercentComplete= 12,7; AccumulatedFeatures= 0; ScansProcessed= 9; ScansPerMinute= 90,0
04/26/2021 16:24:00	Scan/Frame= 241; PercentComplete= 25,3; AccumulatedFeatures= 0; ScansProcessed= 19; ScansPerMinute= 190,0
04/26/2021 16:24:00	Scan/Frame= 371; PercentComplete= 38,0; AccumulatedFeatures= 0; ScansProcessed= 29; ScansPerMinute= 290,0
etc.
```

In the start menu, choose Region Settings, then choose "Additional date, time, & regional settings" at the upper right.  Now choose "Change date, time, or number formats", then click "Additional settings".  Here you can change the decimal symbol from a period to a comma.  I can try to make DeconTools smarter about how it handles decimal points, but I'm hopeful this workaround will work for now.

**Comment by Acedon95** [comment]
Thank you so much! It work perfectly fine now.

**Comment by alchemistmatt** [comment]
I'm really surprised that your _scans.csv file had valid data (matching my file perfectly) while your _isos.csv file is empty.  I tried to replicate the conditions by changing the decimal point from a period to a comma on my computer, but then DeconTools reported an error early on while parsing data from a config file, and I thus didn't even get any output files.

Regardless, good to hear that things started working once the system decimal point was defined as a period.
